//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Change4Change.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allocation
    {
        public System.Guid Id { get; set; }
        public System.Guid AllocatedUserId { get; set; }
        public System.Guid AllocatedUserInvestmentId { get; set; }
        public System.Guid AllocatingUserId { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public Nullable<bool> Paid { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
